name: 'Streamline CV: build'
description: 'Automates boring part of job application: builds a fancy CV pdf.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Run image
      uses: abatilo/actions-poetry@v2
    - name: Create and activate virtual environment
      shell: bash
      run: |
        pip install git+https://github.com/achugr/rendercvcl.git
    - name: Render CV and cover letter
      shell: bash
      run: |
        rendercv render config.yaml
      continue-on-error: false
    - name: "Upload Artifact"
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-artifacts
        path: output/*.pdf
        retention-days: 14
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
    - name: Update Comment
      env:
        JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |-
          ![badge]

          Build Successful! Download [CV and cover letter](${{ steps.upload-artifact.outputs.artifact-url }}).

          [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==

